import { useMemo, useState } from 'react'
import { LanguageContext } from '@/hooks/languageContext'

const STORAGE_KEY = 'ims_language'

const translations = {
  en: {
    analytics: 'ANALYTICS',
    masterDataGroup: 'MASTER DATA',
    operations: 'OPERATIONS',
    stockManagement: 'STOCK MANAGEMENT',
    system: 'SYSTEM',
    settingsGroup: 'SETTINGS',
    dashboard: 'Dashboard',
    reporting: 'Reporting',
    auditTrail: 'Audit Trail',
    masterData: 'Master Data',
    dataBarang: 'Product Data',
    dataGudang: 'Warehouse Data',
    dataKontak: 'Contact Data',
    inventory: 'Inventory',
    scanner: 'Scanner',
    transfer: 'Transfer',
    transferStock: 'Stock Transfer',
    stockOpname: 'Stock Opname',
    settings: 'Settings',
    systemSettings: 'System Settings',
    enterpriseInventory: 'Enterprise Inventory',
    dashboardSubtitle: 'Operational inventory overview.',
    masterSubtitle: 'Manage product catalog & master records.',
    inventorySubtitle: 'Real-time stock monitoring.',
    stockCard: 'Stock Card',
    stockCardSubtitle: 'Detailed movement history.',
    stockIn: 'Stock In',
    stockInSubtitle: 'Receive new items to warehouse.',
    stockOut: 'Stock Out',
    stockOutSubtitle: 'Issue items from warehouse.',
    scannerSubtitle: 'Scan QR or Barcode for quick actions.',
    transfers: 'Transfers',
    transferSubtitle: 'Manage warehouse transfers.',
    stockOpnameSubtitle: 'Reconcile physical stock.',
    createTransfer: 'Create Transfer',
    createTransferSubtitle: 'Move items between warehouses.',
    reviewTransfer: 'Review Transfer',
    reviewTransferSubtitle: 'Review and approve transfer.',
    newStockOpname: 'New Stock Opname',
    newStockOpnameSubtitle: 'Record physical counts.',
    reports: 'Reports',
    reportsSubtitle: 'Inventory reporting & analytics.',
    auditSubtitle: 'Track system activity.',
    settingsSubtitle: 'System configuration.',
    transferDetail: 'Transfer Detail',
    transferDetailSubtitle: 'View transfer record.',
    opnameDetail: 'Opname Detail',
    opnameDetailSubtitle: 'View opname record.',
    searchPlaceholder: 'Search stock, SKU, transfer...',
    searchComingSoon: 'Global search coming soon',
    notifications: 'Notifications',
    unreadAlert: 'unread alert',
    refresh: 'Refresh',
    loadingNotifications: 'Loading notifications...',
    noNotifications: 'No notifications yet.',
    read: 'Read',
    logout: 'Logout',
    home: 'Home',
    master: 'Master',
    scan: 'Scan',
    items: 'Items',
    languageSettings: 'Language Settings',
    languageDescription: 'Choose the interface language used by navigation and system pages.',
    language: 'Language',
    languageSaved: 'Language preference is saved on this device.',
    systemFallback: 'Enterprise Inventory System',
    profile: 'Profile',
    settingsGeneral: 'General',
    settingsCompany: 'Company',
    settingsInventory: 'Inventory',
    settingsNotification: 'Notification',
    settingsSecurity: 'Security',
    settingsBackup: 'Backup',
    userManagement: 'User Management',
    rolePermission: 'Role Permission',
    settingsApi: 'API',
    profileSettings: 'Profile',
    profileDescription: 'Review the active account identity used in this workspace.',
    fullName: 'Full Name',
    email: 'Email',
    role: 'Role',
    active: 'Active',
    verified: 'Verified',
    switchAccount: 'Switch Account',
    accountSecurity: 'Account & Session',
    accountSecurityDescription: 'Manage session actions from the profile menu in the top navigation.',
    activeSession: 'Active Session',
    activeSessionDescription: 'This browser is currently signed in and can access protected IMS pages.',
    switchAccountDescription: 'Use Switch Account from the profile dropdown to return to login and use another account.',
    appPreferences: 'Application Preferences',
    appPreferencesDescription: 'Local interface settings for this device.',
    notificationPreferenceDescription: 'Notification access remains available from the bell icon in the top navigation.',
    localPreferences: 'Local Preferences',
    localPreferencesDescription: 'Language preference is stored locally and does not change database records.',
    english: 'English',
    indonesian: 'Indonesian',
    indonesianOptionDescription: 'Indonesian for navigation and system pages.',
    englishOptionDescription: 'English for navigation and system pages.',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    update: 'Update',
    cancel: 'Cancel',
    done: 'Done',
    download: 'Download',
    export: 'Export',
    import: 'Import',
    search: 'Search',
    start: 'Start',
    stop: 'Stop',
    loading: 'Loading...',
    saving: 'Saving...',
    processing: 'Processing...',
    records: 'records',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    action: 'Action',
    totalRecords: 'Total Records',
    loadedRows: 'Loaded Rows',
    activeRows: 'Active Rows',
    inactiveRows: 'Inactive Rows',
    activeRowsShort: 'Active',
    inactiveRowsShort: 'Inactive',
    allWarehouses: 'All Warehouses',
    allCategories: 'All Categories',
    allStatuses: 'All Statuses',
    allStatus: 'All Status',
    allTypes: 'All Types',
    allDates: 'All Dates',
    searchSkuProduct: 'Search SKU or product...',
    searchProducts: 'Search products...',
    searchReferenceProducts: 'Search reference, products...',
    noDataActiveFilters: 'No data found for the active filters.',
    noInventoryData: 'No inventory data found.',
    noReportData: 'No report data found for the selected filters.',
    noLowStockData: 'No low stock data.',
    noActivities: 'No activities yet.',
    product: 'Product',
    products: 'Products',
    contact: 'Contact',
    contactMaster: 'Contact Master',
    contactMasterDescription: 'Supplier and customer contact data is reserved for the next business module. Database changes are not added until the schema is approved.',
    productMaster: 'Product Master',
    productName: 'Product Name',
    category: 'Category',
    categories: 'Categories',
    categoryMaster: 'Category Master',
    unit: 'Unit',
    units: 'Units',
    unitMaster: 'Unit Master',
    warehouse: 'Warehouse',
    warehouses: 'Warehouses',
    warehouseMaster: 'Warehouse Master',
    barcode: 'Barcode',
    name: 'Name',
    description: 'Description',
    symbol: 'Symbol',
    code: 'Code',
    manager: 'Manager',
    address: 'Address',
    status: 'Status',
    minimum: 'Minimum',
    minimumStock: 'Minimum Stock',
    minStock: 'Min Stock',
    currentStock: 'Current Stock',
    inventoryValue: 'Inventory Value',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    pendingTransfer: 'Pending Transfer',
    totalSku: 'Total SKU',
    totalInventory: 'Total Inventory',
    lowStockItems: 'Low Stock Items',
    recentActivities: 'Recent Activities',
    viewAll: 'View all',
    viewAllLowStock: 'View all low stock',
    unitsCount: 'Units',
    locations: 'Locations',
    movementLedger: 'Movement Ledger',
    fifoBatches: 'FIFO Batches',
    reference: 'Reference',
    referenceNo: 'Reference No',
    type: 'Type',
    quantity: 'Quantity',
    qty: 'Qty',
    balance: 'Balance',
    remaining: 'Remaining',
    cost: 'Cost',
    date: 'Date',
    value: 'Value',
    source: 'Source',
    destination: 'Destination',
    sourceWarehouse: 'Source Warehouse',
    destinationWarehouse: 'Destination Warehouse',
    transferNo: 'Transfer No',
    opnameNo: 'Opname No',
    totalQty: 'Total Qty',
    diffItems: 'Diff Items',
    totalDiff: 'Total Diff',
    stockReport: 'Stock Report',
    movementReport: 'Movement Report',
    transferReport: 'Transfer Report',
    opnameReport: 'Opname Report',
    stock: 'Stock',
    movement: 'Movement',
    opname: 'Opname',
    exportNote: 'Export retrieves up to the first 1,000 rows according to active filters.',
    exportDialogDescription: 'Choose the date range for the data to export. Other active filters will still apply.',
    startDate: 'Start date',
    endDate: 'End date',
    days: 'days',
    selectProduct: 'Select product',
    selectWarehouse: 'Select warehouse',
    selectCategory: 'Select category',
    selectUnit: 'Select unit',
    costMethod: 'Cost method',
    unitCost: 'Unit Cost',
    locationBin: 'Location Bin',
    receivedDate: 'Received Date',
    scanBarcode: 'Scan Barcode',
    receivingForm: 'Receiving Form',
    issuingForm: 'Issuing Form',
    inputStockIn: 'Input Stock In',
    inputStockOut: 'Input Stock Out',
    availableQty: 'Available qty',
    chooseProductWarehouse: 'Select product and warehouse',
    confirmStockIn: 'Confirm Stock In',
    confirmStockOut: 'Confirm Stock Out',
    saveStockIn: 'Save Stock In',
    saveStockOut: 'Save Stock Out',
    scannerView: 'Scanner View',
    productDetail: 'Product Detail',
    quickAction: 'Quick Action',
    cameraStopped: 'Camera is stopped',
    clickStartScan: 'Click Start to scan barcodes',
    manualBarcode: 'Manual entry barcode...',
    scanBarcodeProductDetail: 'Scan a barcode to view product details',
    location: 'Location',
    loginTitle: 'Sign in to IMS',
    loginDescription: 'Use the demo account from the database seeder.',
    password: 'Password',
    loginSubmit: 'Sign in',
    loginHeroTitle: 'Multi-warehouse, fast scanning, secure ledger.',
    loginHeroDescription: 'Desktop mode is designed for monitoring, approvals, and inventory operations that need a wider workspace.',
    todaySnapshot: 'Today snapshot',
    alert: 'Alert',
    normal: 'Normal',
    draft: 'Draft',
    counting: 'Counting',
    review: 'Review',
    approved: 'Approved',
    inTransit: 'In Transit',
    adjusted: 'Adjusted',
    received: 'Received',
    completed: 'Completed',
    rejected: 'Rejected',
    workflow: 'Workflow',
    stockMovement: 'Stock Movement',
    operationalMix: 'Operational Mix',
    operationalMixSubtitle: 'Current dashboard alert composition',
    movementTrendSubtitle: 'Inbound, outbound, and transfer from recent activity',
    loginBenefitRealtime: 'Realtime warehouse visibility',
    loginBenefitScanner: 'Barcode and QR assisted operations',
    loginBenefitLedger: 'Auditable stock movement ledger',
    adjustment: 'Adjustment',
    stockInStatus: 'Stock In',
    stockOutStatus: 'Stock Out',
    transferIn: 'Transfer In',
    transferOut: 'Transfer Out',
    sortPrefix: 'Sort',
    productNameAZ: 'Product Name A-Z',
    productNameZA: 'Product Name Z-A',
    warehouseAZ: 'Warehouse A-Z',
    warehouseZA: 'Warehouse Z-A',
    minStockLowHigh: 'Min Stock Low-High',
    minStockHighLow: 'Min Stock High-Low',
    currentStockLowHigh: 'Current Stock Low-High',
    currentStockHighLow: 'Current Stock High-Low',
    statusAZ: 'Status A-Z',
    statusZA: 'Status Z-A',
    dataUpdated: 'Data updated successfully.',
    dataCreated: 'Data created successfully.',
    dataDeleted: 'Data deleted successfully.',
    dataSaveFailed: 'Data failed to save.',
    dataDeleteFailed: 'Data failed to delete.',
    formDetails: 'Form details.',
    increase: 'Increase',
    decrease: 'Decrease',
    atWarehouse: 'at',
    movementLedgerNote: 'The transaction will be recorded in the movement ledger.',
    page: 'Page',
    total: 'Total',
    detail: 'Detail',
    noTransferData: 'No transfer data found.',
    noOpnameData: 'No opname session found.',
    totalSession: 'Total Session',
    needReview: 'Need Review',
    createSession: 'Create Session',
    sessionNo: 'Session No',
    officer: 'Officer',
    countAndApproval: 'Count & Approval',
    transferInfo: 'Transfer Information',
    transferMutationTitle: 'Inter-Warehouse Transfer',
    transferQuantity: 'Transfer Quantity',
    confirmTransfer: 'Confirm Transfer',
    confirmTransferDescription: 'Make sure source warehouse, destination warehouse, and item quantity are correct before submitting.',
    verifyTransfer: 'I have verified this transfer',
    verifyTransferDescription: 'Confirming this action will create a draft for approval.',
    createDraft: 'Create Draft',
    back: 'Back',
    approveTransfer: 'Approve Transfer',
    reject: 'Reject',
    receiveItems: 'Receive Items',
    markInTransit: 'Mark In Transit',
    completeTransfer: 'Complete Transfer',
    transferApprovedMessage: 'Transfer approved and source stock reduced.',
    transferInTransitMessage: 'Transfer marked as in transit.',
    transferRejectedMessage: 'Transfer rejected successfully.',
    transferReceivedMessage: 'Transfer received and destination stock increased.',
    transferCompletedMessage: 'Transfer completed successfully.',
    auditActivityLedger: 'Activity Ledger',
    logsRecorded: 'logs recorded',
    allUsers: 'All Users',
    allActions: 'All Actions',
    dateRange: 'Date Range',
    selectDate: 'Select date...',
    dateTime: 'Date & Time',
    table: 'Table',
    recordId: 'Record ID',
    details: 'Details',
    view: 'View',
    viewDetails: 'View Details',
    auditNotFound: 'Audit trail not found.',
    logs: 'logs',
    auditDetail: 'Audit Detail',
    auditDetailDescription: 'System activity details',
    userInformation: 'User Information',
    actionTarget: 'Action & Target',
    oldValues: 'Old Values (Before)',
    newValues: 'New Values (After)',
    noChangesRecorded: 'No changes recorded',
  },
  id: {
    analytics: 'ANALITIK',
    masterDataGroup: 'DATA MASTER',
    operations: 'OPERASIONAL',
    stockManagement: 'MANAJEMEN STOK',
    system: 'SISTEM',
    settingsGroup: 'PENGATURAN',
    dashboard: 'Dashboard',
    reporting: 'Laporan',
    auditTrail: 'Jejak Audit',
    masterData: 'Data Master',
    dataBarang: 'Data Barang',
    dataGudang: 'Data Gudang',
    dataKontak: 'Data Kontak',
    inventory: 'Inventori',
    scanner: 'Pemindai',
    transfer: 'Transfer',
    transferStock: 'Transfer Stok',
    stockOpname: 'Stok Opname',
    settings: 'Pengaturan',
    systemSettings: 'Pengaturan Sistem',
    enterpriseInventory: 'Inventori Enterprise',
    dashboardSubtitle: 'Ringkasan operasional inventori.',
    masterSubtitle: 'Kelola katalog produk dan data master.',
    inventorySubtitle: 'Monitoring stok real-time.',
    stockCard: 'Kartu Stok',
    stockCardSubtitle: 'Riwayat mutasi stok detail.',
    stockIn: 'Barang Masuk',
    stockInSubtitle: 'Terima barang baru ke gudang.',
    stockOut: 'Barang Keluar',
    stockOutSubtitle: 'Keluarkan barang dari gudang.',
    scannerSubtitle: 'Pindai QR atau barcode untuk aksi cepat.',
    transfers: 'Transfer',
    transferSubtitle: 'Kelola transfer antar gudang.',
    stockOpnameSubtitle: 'Rekonsiliasi stok fisik.',
    createTransfer: 'Buat Transfer',
    createTransferSubtitle: 'Pindahkan barang antar gudang.',
    reviewTransfer: 'Tinjau Transfer',
    reviewTransferSubtitle: 'Tinjau dan setujui transfer.',
    newStockOpname: 'Stok Opname Baru',
    newStockOpnameSubtitle: 'Catat hasil perhitungan fisik.',
    reports: 'Laporan',
    reportsSubtitle: 'Laporan dan analitik inventori.',
    auditSubtitle: 'Pantau aktivitas sistem.',
    settingsSubtitle: 'Konfigurasi sistem.',
    transferDetail: 'Detail Transfer',
    transferDetailSubtitle: 'Lihat record transfer.',
    opnameDetail: 'Detail Opname',
    opnameDetailSubtitle: 'Lihat record opname.',
    searchPlaceholder: 'Cari stok, SKU, transfer...',
    searchComingSoon: 'Pencarian global segera hadir',
    notifications: 'Notifikasi',
    unreadAlert: 'notifikasi belum dibaca',
    refresh: 'Muat ulang',
    loadingNotifications: 'Memuat notifikasi...',
    noNotifications: 'Belum ada notifikasi.',
    read: 'Baca',
    logout: 'Keluar',
    home: 'Beranda',
    master: 'Master',
    scan: 'Pindai',
    items: 'Barang',
    languageSettings: 'Pengaturan Bahasa',
    languageDescription: 'Pilih bahasa antarmuka untuk navigasi dan halaman sistem.',
    language: 'Bahasa',
    languageSaved: 'Preferensi bahasa tersimpan di perangkat ini.',
    systemFallback: 'Sistem Inventori Enterprise',
    profile: 'Profil',
    settingsGeneral: 'Umum',
    settingsCompany: 'Perusahaan',
    settingsInventory: 'Inventori',
    settingsNotification: 'Notifikasi',
    settingsSecurity: 'Keamanan',
    settingsBackup: 'Backup',
    userManagement: 'Manajemen Pengguna',
    rolePermission: 'Peran & Hak Akses',
    settingsApi: 'API',
    profileSettings: 'Profil',
    profileDescription: 'Lihat identitas akun aktif yang digunakan di workspace ini.',
    fullName: 'Nama Lengkap',
    email: 'Email',
    role: 'Role',
    active: 'Aktif',
    verified: 'Terverifikasi',
    switchAccount: 'Ganti Akun',
    accountSecurity: 'Akun & Sesi',
    accountSecurityDescription: 'Kelola aksi sesi dari menu profil di navigasi atas.',
    activeSession: 'Sesi Aktif',
    activeSessionDescription: 'Browser ini sedang login dan dapat mengakses halaman IMS yang terlindungi.',
    switchAccountDescription: 'Gunakan Ganti Akun dari dropdown profil untuk kembali ke login dan memakai akun lain.',
    appPreferences: 'Preferensi Aplikasi',
    appPreferencesDescription: 'Pengaturan antarmuka lokal untuk perangkat ini.',
    notificationPreferenceDescription: 'Akses notifikasi tetap tersedia dari icon lonceng di navigasi atas.',
    localPreferences: 'Preferensi Lokal',
    localPreferencesDescription: 'Preferensi bahasa disimpan lokal dan tidak mengubah record database.',
    english: 'Inggris',
    indonesian: 'Indonesia',
    indonesianOptionDescription: 'Bahasa Indonesia untuk navigasi dan halaman sistem.',
    englishOptionDescription: 'Bahasa Inggris untuk navigasi dan halaman sistem.',
    add: 'Tambah',
    edit: 'Edit',
    delete: 'Hapus',
    save: 'Simpan',
    update: 'Perbarui',
    cancel: 'Batal',
    done: 'Selesai',
    download: 'Unduh',
    export: 'Ekspor',
    import: 'Impor',
    search: 'Cari',
    start: 'Mulai',
    stop: 'Berhenti',
    loading: 'Memuat...',
    saving: 'Menyimpan...',
    processing: 'Memproses...',
    records: 'data',
    showing: 'Menampilkan',
    to: 'sampai',
    of: 'dari',
    previous: 'Sebelumnya',
    next: 'Berikutnya',
    action: 'Aksi',
    totalRecords: 'Total Data',
    loadedRows: 'Baris Dimuat',
    activeRows: 'Baris Aktif',
    inactiveRows: 'Baris Nonaktif',
    activeRowsShort: 'Aktif',
    inactiveRowsShort: 'Nonaktif',
    allWarehouses: 'Semua Gudang',
    allCategories: 'Semua Kategori',
    allStatuses: 'Semua Status',
    allStatus: 'Semua Status',
    allTypes: 'Semua Tipe',
    allDates: 'Semua Tanggal',
    searchSkuProduct: 'Cari SKU atau produk...',
    searchProducts: 'Cari produk...',
    searchReferenceProducts: 'Cari referensi, produk...',
    noDataActiveFilters: 'Data tidak ditemukan untuk filter aktif.',
    noInventoryData: 'Data inventori tidak ditemukan.',
    noReportData: 'Data laporan tidak ditemukan untuk filter terpilih.',
    noLowStockData: 'Tidak ada data stok rendah.',
    noActivities: 'Belum ada aktivitas.',
    product: 'Produk',
    products: 'Produk',
    contact: 'Kontak',
    contactMaster: 'Master Kontak',
    contactMasterDescription: 'Data pemasok dan pelanggan disiapkan sebagai modul bisnis berikutnya. Perubahan database belum ditambahkan sampai skema disetujui.',
    productMaster: 'Master Produk',
    productName: 'Nama Produk',
    category: 'Kategori',
    categories: 'Kategori',
    categoryMaster: 'Master Kategori',
    unit: 'Satuan',
    units: 'Satuan',
    unitMaster: 'Master Satuan',
    warehouse: 'Gudang',
    warehouses: 'Gudang',
    warehouseMaster: 'Master Gudang',
    barcode: 'Barcode',
    name: 'Nama',
    description: 'Deskripsi',
    symbol: 'Simbol',
    code: 'Kode',
    manager: 'Penanggung Jawab',
    address: 'Alamat',
    status: 'Status',
    minimum: 'Minimum',
    minimumStock: 'Stok Minimum',
    minStock: 'Stok Min.',
    currentStock: 'Stok Saat Ini',
    inventoryValue: 'Nilai Inventori',
    lowStock: 'Stok Rendah',
    outOfStock: 'Stok Habis',
    inStock: 'Stok Tersedia',
    pendingTransfer: 'Transfer Tertunda',
    totalSku: 'Total SKU',
    totalInventory: 'Total Inventori',
    lowStockItems: 'Barang Stok Rendah',
    recentActivities: 'Aktivitas Terbaru',
    viewAll: 'Lihat semua',
    viewAllLowStock: 'Lihat semua stok rendah',
    unitsCount: 'Unit',
    locations: 'Lokasi',
    movementLedger: 'Buku Mutasi',
    fifoBatches: 'Batch FIFO',
    reference: 'Referensi',
    referenceNo: 'No. Referensi',
    type: 'Tipe',
    quantity: 'Kuantitas',
    qty: 'Qty',
    balance: 'Saldo',
    remaining: 'Sisa',
    cost: 'Biaya',
    date: 'Tanggal',
    value: 'Nilai',
    source: 'Asal',
    destination: 'Tujuan',
    sourceWarehouse: 'Gudang Asal',
    destinationWarehouse: 'Gudang Tujuan',
    transferNo: 'No. Transfer',
    opnameNo: 'No. Opname',
    totalQty: 'Total Qty',
    diffItems: 'Item Selisih',
    totalDiff: 'Total Selisih',
    stockReport: 'Laporan Stok',
    movementReport: 'Laporan Mutasi',
    transferReport: 'Laporan Transfer',
    opnameReport: 'Laporan Opname',
    stock: 'Stok',
    movement: 'Mutasi',
    opname: 'Opname',
    exportNote: 'Ekspor mengambil maksimal 1.000 baris pertama sesuai filter aktif.',
    exportDialogDescription: 'Pilih rentang tanggal untuk data yang ingin diekspor. Filter aktif lainnya tetap digunakan.',
    startDate: 'Tanggal mulai',
    endDate: 'Tanggal akhir',
    days: 'hari',
    selectProduct: 'Pilih produk',
    selectWarehouse: 'Pilih gudang',
    selectCategory: 'Pilih kategori',
    selectUnit: 'Pilih satuan',
    costMethod: 'Metode biaya',
    unitCost: 'Biaya Satuan',
    locationBin: 'Lokasi Rak',
    receivedDate: 'Tanggal Terima',
    scanBarcode: 'Pindai Barcode',
    receivingForm: 'Form Barang Masuk',
    issuingForm: 'Form Barang Keluar',
    inputStockIn: 'Input Barang Masuk',
    inputStockOut: 'Input Barang Keluar',
    availableQty: 'Qty tersedia',
    chooseProductWarehouse: 'Pilih produk dan gudang',
    confirmStockIn: 'Konfirmasi Barang Masuk',
    confirmStockOut: 'Konfirmasi Barang Keluar',
    saveStockIn: 'Simpan Barang Masuk',
    saveStockOut: 'Simpan Barang Keluar',
    scannerView: 'Tampilan Pemindai',
    productDetail: 'Detail Produk',
    quickAction: 'Aksi Cepat',
    cameraStopped: 'Kamera berhenti',
    clickStartScan: 'Klik Mulai untuk memindai barcode',
    manualBarcode: 'Input barcode manual...',
    scanBarcodeProductDetail: 'Pindai barcode untuk melihat detail produk',
    location: 'Lokasi',
    loginTitle: 'Masuk IMS',
    loginDescription: 'Gunakan akun demo dari database seeder.',
    password: 'Kata Sandi',
    loginSubmit: 'Masuk',
    loginHeroTitle: 'Multi-gudang, pindai cepat, ledger aman.',
    loginHeroDescription: 'Mode desktop dirancang untuk monitoring, approval, dan operasi inventori yang butuh ruang kerja lebih luas.',
    todaySnapshot: 'Ringkasan hari ini',
    alert: 'Peringatan',
    normal: 'Normal',
    draft: 'Draf',
    counting: 'Penghitungan',
    review: 'Tinjauan',
    approved: 'Disetujui',
    inTransit: 'Dalam Pengiriman',
    adjusted: 'Disesuaikan',
    received: 'Diterima',
    completed: 'Selesai',
    rejected: 'Ditolak',
    workflow: 'Alur Kerja',
    stockMovement: 'Mutasi Stok',
    operationalMix: 'Komposisi Operasional',
    operationalMixSubtitle: 'Komposisi peringatan dashboard saat ini',
    movementTrendSubtitle: 'Barang masuk, keluar, dan transfer dari aktivitas terbaru',
    loginBenefitRealtime: 'Visibilitas gudang real-time',
    loginBenefitScanner: 'Operasi dibantu barcode dan QR',
    loginBenefitLedger: 'Ledger mutasi stok yang dapat diaudit',
    adjustment: 'Penyesuaian',
    stockInStatus: 'Barang Masuk',
    stockOutStatus: 'Barang Keluar',
    transferIn: 'Transfer Masuk',
    transferOut: 'Transfer Keluar',
    sortPrefix: 'Urutkan',
    productNameAZ: 'Nama Produk A-Z',
    productNameZA: 'Nama Produk Z-A',
    warehouseAZ: 'Gudang A-Z',
    warehouseZA: 'Gudang Z-A',
    minStockLowHigh: 'Stok Min. Rendah-Tinggi',
    minStockHighLow: 'Stok Min. Tinggi-Rendah',
    currentStockLowHigh: 'Stok Saat Ini Rendah-Tinggi',
    currentStockHighLow: 'Stok Saat Ini Tinggi-Rendah',
    statusAZ: 'Status A-Z',
    statusZA: 'Status Z-A',
    dataUpdated: 'Data berhasil diperbarui.',
    dataCreated: 'Data berhasil dibuat.',
    dataDeleted: 'Data berhasil dihapus.',
    dataSaveFailed: 'Data gagal disimpan.',
    dataDeleteFailed: 'Data gagal dihapus.',
    formDetails: 'Detail form.',
    increase: 'Tambah',
    decrease: 'Kurangi',
    atWarehouse: 'di',
    movementLedgerNote: 'Transaksi akan tercatat di ledger mutasi.',
    page: 'Halaman',
    total: 'Total',
    detail: 'Detail',
    noTransferData: 'Data transfer tidak ditemukan.',
    noOpnameData: 'Sesi opname tidak ditemukan.',
    totalSession: 'Total Sesi',
    needReview: 'Perlu Tinjauan',
    createSession: 'Buat Sesi',
    sessionNo: 'No. Sesi',
    officer: 'Petugas',
    countAndApproval: 'Hitung & Persetujuan',
    transferInfo: 'Informasi Transfer',
    transferMutationTitle: 'Mutasi Antar-Gudang',
    transferQuantity: 'Kuantitas Transfer',
    confirmTransfer: 'Konfirmasi Transfer',
    confirmTransferDescription: 'Pastikan gudang asal, gudang tujuan, dan kuantitas barang sudah sesuai sebelum diajukan.',
    verifyTransfer: 'Saya sudah memverifikasi transfer ini',
    verifyTransferDescription: 'Konfirmasi ini akan membuat draf untuk persetujuan.',
    createDraft: 'Buat Draf',
    back: 'Kembali',
    approveTransfer: 'Setujui Transfer',
    reject: 'Tolak',
    receiveItems: 'Terima Barang',
    markInTransit: 'Tandai Dikirim',
    completeTransfer: 'Selesaikan Transfer',
    transferApprovedMessage: 'Transfer berhasil disetujui dan stok asal dikurangi.',
    transferInTransitMessage: 'Transfer ditandai sedang dikirim.',
    transferRejectedMessage: 'Transfer berhasil ditolak.',
    transferReceivedMessage: 'Transfer berhasil diterima dan stok tujuan ditambah.',
    transferCompletedMessage: 'Transfer berhasil diselesaikan.',
    auditActivityLedger: 'Catatan Aktivitas',
    logsRecorded: 'log tercatat',
    allUsers: 'Semua Pengguna',
    allActions: 'Semua Aksi',
    dateRange: 'Rentang Tanggal',
    selectDate: 'Pilih tanggal...',
    dateTime: 'Tanggal & Waktu',
    table: 'Tabel',
    recordId: 'ID Rekaman',
    details: 'Detail',
    view: 'Lihat',
    viewDetails: 'Lihat Detail',
    auditNotFound: 'Jejak audit tidak ditemukan.',
    logs: 'log',
    auditDetail: 'Detail Audit',
    auditDetailDescription: 'Rincian aktivitas sistem',
    userInformation: 'Informasi Pengguna',
    actionTarget: 'Aksi & Target',
    oldValues: 'Nilai Lama (Sebelum)',
    newValues: 'Nilai Baru (Sesudah)',
    noChangesRecorded: 'Tidak ada perubahan tercatat',
  },
}

function getStoredLanguage() {
  const stored = window.localStorage.getItem(STORAGE_KEY)
  return stored === 'en' || stored === 'id' ? stored : 'id'
}

function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(getStoredLanguage)

  function setLanguage(nextLanguage) {
    const safeLanguage = nextLanguage === 'en' ? 'en' : 'id'
    window.localStorage.setItem(STORAGE_KEY, safeLanguage)
    setLanguageState(safeLanguage)
  }

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: translations[language],
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export default LanguageProvider
